services:

  api:
    build: .
    container_name: todo-api
    ports:
      - "8080:3000"
    restart: on-failure
    depends_on:
      - db

  db:
    image: mysql
    container_name: todo-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}